language: android
sudo: true
jdk: oraclejdk8
android:
    components:
        - tools
        - platform-tools
        - build-tools-24.0.2
        - android-24
        - extra-android-m2repository
    licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'

script:
  - ./gradlew javadocrelease
  - ./gradlew jarrelease
  - ./gradlew bintrayUpload

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file:
    - b-log/build/libs/b-log-${TRAVIS_TAG}-javadoc.jar
    - b-log/build/libs/b-log-${TRAVIS_TAG}.jar
  skip_cleanup: true
  on:
    tags: true

branches:
  only:
  - /$bintrayUpload/