language: android
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

script:
  - ./gradlew javadocrelease
  # - ./gradlew bintrayUpload

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file: ${JAR_PATH}
  skip_cleanup: true
  on:
    tags: true

env:
 global:
   - JAR_PATH: library/build/libs
