language: android
jdk:
  - oraclejdk8

android:
  components:
    - build-tools-23.0.0
    - android-23
    - android-L
    - sys-img-x86-android-tv-l
    - add-on
    - extra

script:
  - ./gradlew javadocrelease
  # - ./gradlew bintrayUpload

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file: ${JAR_PATH}
  skip_cleanup: true
  on:
    tags: true

env:
 global:
   - JAR_PATH: library/build/libs
