language: android
sudo: true
jdk: oraclejdk8
android:
    components:
        - tools
        - platform-tools
        - build-tools-24.0.2
        - android-24
        - extra-android-m2repository
    licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'

script:
  - ./gradlew javadocrelease
  # - ./gradlew bintrayUpload

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file: ${JAR_PATH}
  skip_cleanup: true
  on:
    tags: true

env:
 global:
   - JAR_PATH: library/build/libs
