language: android
jdk: oraclejdk8
language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25.1.x (x = 6 right now)
     # rest

script:
  - ./gradlew javadocrelease
  # - ./gradlew bintrayUpload

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file: ${JAR_PATH}
  skip_cleanup: true
  on:
    tags: true

env:
 global:
   - JAR_PATH: library/build/libs
